apiVersion: plugin.halo.run/v1alpha1
kind: ExtensionDefinition
metadata:
  name: katex-post-injection
spec:
  className: run.halo.katex.DefaultPostContentHandler
  extensionPointName: reactive-post-content-handler
  displayName: "DefaultPostContentHandler"
  description: "KaTeX scripts injection for post content."

---

apiVersion: plugin.halo.run/v1alpha1
kind: ExtensionDefinition
metadata:
  name: katex-singlepage-injection
spec:
  className: run.halo.katex.DefaultSinglePageContentHandler
  extensionPointName: reactive-singlepage-content-handler
  displayName: "DefaultSinglePageContentHandler"
  description: "KaTeX scripts injection for single page content."