apiVersion: plugin.halo.run/v1alpha1
kind: Plugin
metadata:
  name: plugin-katex
spec:
  enabled: true
  requires: ">=2.7.0"
  author:
    name: Halo OSS Team
    website: https://github.com/halo-dev
  logo: logo.png
  homepage: https://github.com/halo-sigs/plugin-katex
  displayName: "KaTeX"
  description: "为编辑器和文章渲染提供 KaTeX 支持"
  license:
    - name: "GPL-3.0"
      url: "https://github.com/halo-sigs/plugin-katex/blob/main/LICENSE"
